version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_pass
      POSTGRES_DB: lasuads_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  postgres_data: